### ISSUE TITLE
How hard would it be to add support from Travis CI?

### ISSUE THREAD

**Issue by EuAndreh** [cl-test-grid/cl-test-grid#24]
The README mentions `setting up a central build farm with all the possible hardware/OS/Lisp implementation combinations`. Using [Travis CI](https://travis-ci.org/) it is possible to (freely) set up a central build farm with all the possible **Lisp implementation** combinations.

How do you feel about that?

**Comment by avodonosov** [comment]
Travis CI is similar to cl-test-grid.
There is already https://github.com/luismbo/cl-travis

The difference between Travis CI and cl-test-grid is that Travis CI monitors your library isolated, while cl-test-grid monitors the all the libraries as a whole. If for example, alexandria library changes, Travic CI will test alexandria, but won't test all the alexandria-dependent lbiraries. cl-test-grid retests whole quicklisp distro, so if alexandria change breaks some other library we detect it.

Also (less important) Travis CI only runs tests on linux, in cl-test-grid we collect results from various OSes.

**Comment by avodonosov** [comment]
Ah, yes, maybe more related to your question: I've been thinking to piggyback on Travis CI, but not sure about it.

I mentioned one problem already - when to re-run tests. Travis CI does it upon commit, but we re-test even when dependencies changed (or when new QL distro is out - it captures new dependencies).
But we can't retest whole Quicklisp in Travis CI because of 20 minutes time limit.

I am watching cl-travis project. Maybe when it will be ready I will ask luish to submit the test result to cl-test-grid database (in addition to returning it to Travis).
